version: '3.8'

services:
  fl-server:
    build: ./fl-server
    ports:
      - "8001:8001"
    volumes:
      - ./fl-server/db.json:/app/db.json

  dashboard-api:
    build: ./dashboard-api
    ports:
      - "3001:3001"
    depends_on:
      - fl-server

  dashboard-app:
    build: ./dashboard-app
    ports:
      - "3000:3000"
